Controllers/AuctionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using RetroGamesAuction1.Models;
using RetroGamesAuction1.Models.ViewModel;
using System.Linq.Expressions;
using NuGet.Packaging.Signing;
using System;
using System.Linq;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using RetroGamesAuction1.Services;

namespace RetroGamesAuction1.Controllers
{
    [Authorize]
    public class AuctionController : Controller
    {


        private readonly AuctionService _auctionService;
        public AuctionController(AuctionService auctionService)
        {

            _auctionService = auctionService;
        }

        // GET: Catalog1Controller
        public ActionResult Index(string searchBy, string searchValue)

        {

            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(_auctionService.SelectAuction());
            }
            else
            {
                if (searchBy.ToLower() == "productname")
                {
                    var searchByProductName = _auctionService.SelectAuction().Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "articul")
                {
                    var searchByProductArticul = _auctionService.SelectAuction().Where(p => p.Articul.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductArticul);
                }
                else if (searchBy.ToLower() == "beginbid")
                {
                    var searchByProductCost = _auctionService.SelectAuction().Where(c => c.Beginbid == int.Parse(searchValue));
                    return View(searchByProductCost);
                }
            }
            return View(_auctionService.SelectAuction());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AllIndex(string searchBy, string searchValue)

        {

            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(_auctionService.SelectAuction());
            }
            else
            {
                if (searchBy.ToLower() == "productname")
                {
                    var searchByProductName = _auctionService.SelectAuction().Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "articul")
                {
                    var searchByProductArticul = _auctionService.SelectAuction().Where(p => p.Articul.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductArticul);
                }
                else if (searchBy.ToLower() == "beginbid")
                {
                    var searchByProductCost = _auctionService.SelectAuction().Where(c => c.Beginbid == int.Parse(searchValue));
                    return View(searchByProductCost);
                }
            }
            return View(_auctionService.SelectAuction());
        }

        public ActionResult Details(int id)
        {
            _auctionService.SelectAuctionById(id);

            return View(_auctionService.SelectAuctionById(id));
        }
        
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            Auction auction = new Auction();

            return View(auction);
        }

        [Authorize(Roles = "Admin")]
        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Auction auction)
        {
            _auctionService.SaveAuction(auction);
            TempData["AlertMessage"] = "Ayкцион Создан!";
            return RedirectToAction(nameof(AllIndex));
        }

        // GET: AuctionController/Edit/5
        public ActionResult Edit(int id)
        {
            var auction = _auctionService.GetAuctionByID(id);
            return View(auction);
        }

        // POST: AuctionController/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Auction auction,int id)
        {
            var auctionUpdate = _auctionService.GetAuctionByID(id);
            auctionUpdate.Begintime = _auctionService.GetAuctionByID(id).Begintime;
            auctionUpdate.Endtime = _auctionService.GetAuctionByID(id).Endtime;
            auctionUpdate.IdProduct = auction.IdProduct;
            auctionUpdate.Beginbid = auction.Beginbid;

            if (auction != null && auctionUpdate.Begintime.HasValue && auctionUpdate.Endtime.HasValue)
            {
                _auctionService.UpdateAuction(auction);
                TempData["AlertMessage"] = "Аукцион изменен!";
            }
            return RedirectToAction(nameof(AllIndex));
        }
        
        [Authorize(Roles = "Admin")]
        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            _auctionService.RemoveAuction(id);
            TempData["AlertMessage"] = "Aукцион удален!";
            return RedirectToAction(nameof(AllIndex));
        }
        
        [Authorize(Roles = "Admin")]
        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RetroGamesAuction1.Data;
using RetroGamesAuction1.Models;
using System.Data;

namespace RetroGamesAuction1.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        
        private readonly DataApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        
        public ProductController(DataApplicationDbContext context,IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        // GET: Product1Controller
        public ActionResult Index(string searchBy, string searchValue)
        {
            List<Product> products;
            products = _context.Product.ToList();
            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(products);
            }
            else
            {
                if (searchBy.ToLower() == "productname")
                {
                    var searchByProductName = products.Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "articul")
                {
                    var searchByProductArticul = products.Where(p => p.Articul.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductArticul);
                }
                else if (searchBy.ToLower() == "cost")
                {
                    var searchByProductCost = products.Where(p => p.Prise == int.Parse(searchValue));
                    return View(searchByProductCost);
                }
            }
            return View(products);
        }

        // GET: Product1Controller/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductController/Create
        [HttpGet]
        public IActionResult Create()
        {
            Product product = new Product();

            return View(product);
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if(product.Photo1 != null)
            {
                string folder = "lib/product/";
                //создали уникальное имя файла
                folder +=Guid.NewGuid().ToString() + product.Photo1.FileName;
                product.ProductPic = folder;
                string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath,folder);
                await product.Photo1.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                
                string folder1 = "lib/product/";
                //создали уникальное имя файла
                folder1 += Guid.NewGuid().ToString() + product.Photo2.FileName;
                product.ProductPic1 = folder1;
                string serverFolder1 = Path.Combine(_webHostEnvironment.WebRootPath, folder1);
                await product.Photo2.CopyToAsync(new FileStream(serverFolder1, FileMode.Create));
                
                string folder2 = "lib/product/";
                //создали уникальное имя файла
                folder2 += Guid.NewGuid().ToString() + product.Photo3.FileName;
                product.ProductPic2 = folder2;
                string serverFolder2 = Path.Combine(_webHostEnvironment.WebRootPath, folder2);
                await product.Photo3.CopyToAsync(new FileStream(serverFolder2, FileMode.Create));
            }
            _context.Add(product);
            _context.SaveChanges();
            TempData["AlertMessage"] = "Продукт Создан!";
            return RedirectToAction("index");
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {

            Product product = _context.Product.Find(id);
            return View(product);
        }

        // POST: FacturaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Product product)
        {
            try
            {
                Product pr = _context.Product.Find(product.IdProduct);
                pr.IdProduct = product.IdProduct;
                pr.ProductName = product.ProductName;
                pr.Articul = product.Articul;
                pr.Prise = product.Prise;
                pr.Description = product.Description;
                string folder = "lib/product/";
                //создали уникальное имя файла
                folder += Guid.NewGuid().ToString() + product.Photo1.FileName;
                product.ProductPic = folder;
                string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);
                await product.Photo1.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

                string folder1 = "lib/product/";
                //создали уникальное имя файла
                folder1 += Guid.NewGuid().ToString() + product.Photo2.FileName;
                product.ProductPic1 = folder1;
                string serverFolder1 = Path.Combine(_webHostEnvironment.WebRootPath, folder1);
                await product.Photo2.CopyToAsync(new FileStream(serverFolder1, FileMode.Create));

                string folder2 = "lib/product/";
                //создали уникальное имя файла
                folder2 += Guid.NewGuid().ToString() + product.Photo3.FileName;
                product.ProductPic2 = folder2;
                string serverFolder2 = Path.Combine(_webHostEnvironment.WebRootPath, folder2);
                await product.Photo3.CopyToAsync(new FileStream(serverFolder2, FileMode.Create));
                pr.ProductPic1 = product.ProductPic1;
                pr.ProductPic2 = product.ProductPic2;
                pr.ProductPic = product.ProductPic;
                _context.SaveChanges();
                TempData["AlertMessage"] = "Продукт изменен!";
                return RedirectToAction(nameof(Index));
            }
            catch
            {

                return View();
            }
        }

        // GET: ProductController/Delete/5
        public  ActionResult Delete(int id)
        {
            if (id == 0)
            { return NotFound(); }
            else
            {
                var data = _context.Product.Find(id);
                if(data != null)
                {
                    string deleteFromFolder = Path.Combine(_webHostEnvironment.WebRootPath);
                    string currentImage = Path.Combine(deleteFromFolder, data.ProductPic);
                    string currentImage1 = Path.Combine(deleteFromFolder, data.ProductPic1);
                    string currentImage2 = Path.Combine(deleteFromFolder, data.ProductPic2);
                    if (currentImage != null)
                    {
                        if(System.IO.File.Exists(currentImage))
                        {
                             System.IO.File.Delete(currentImage);
                        }
                    }

                    if (currentImage != null)
                    {
                        if (System.IO.File.Exists(currentImage1))
                        {
                            System.IO.File.Delete(currentImage1);
                        }
                    }

                    if (currentImage != null)
                    {
                        if (System.IO.File.Exists(currentImage2))
                        {
                            System.IO.File.Delete(currentImage2);
                        }
                    }
                }
                _context.Product.Remove(data);
                _context.SaveChanges();
                TempData["AlertMessage"] = "Продукт удален!";

            }
            
            return RedirectToAction(nameof(Index));
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}
    

Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using RetroGamesAuction1.Models.ViewModel;
using RetroGamesAuction1.Data;
using LibSassHost;
using Microsoft.AspNetCore.Mvc.Rendering;
using RetroGamesAuction1.Models;

namespace RetroGamesAuction1.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesController(RoleManager<IdentityRole> roleManager,ApplicationDbContext context)
        {
            _context = context;
            _roleManager = roleManager;
        }
        //Создали лист ролей 
        public IActionResult  Index()
        {
            //var roles = _roleManager.Roles.ToList();
            var roles = (from ur in  _context.UserRoles
                         join r in _context.Roles
                         on ur.RoleId equals r.Id
                         join u in _context.Users
                         on ur.UserId equals u.Id
                         select new ListViewModel1
                         {
                             RoleId = r.Id,
                             RoleName = r.Name,
                             UserId = u.Id,
                             UserName = u.UserName


                         }).ToList();

            return View(roles);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult>Create(IdentityRole model)
        {
           

            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                
                {
                    _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
                }
                
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RetroGamesAuction</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RetroGamesAuction1.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/icon2.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                           
                        <li><a class="nav-link text-light" id="link1" asp-area="" asp-controller="Auction" asp-action="Index">Аукцион</a></li>
                        <li><a class="nav-link text-light" id="link1" asp-area="" asp-controller="Auctionbid" asp-action="DetailsID">Мои ставки</a></li>
                        
                        <li><a class="nav-link text-light" id="link1" asp-area="" asp-controller="Auctionbid" asp-action="Index">Ставки</a></li>
                        @if(User.IsInRole("Admin"))
                        {
                            <li><a class="nav-link text-light" id="link1" asp-area="" asp-controller="Auctionbid" asp-action="Admin">Админ Панель</a></li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-transparent-0.5 border-bottom box-shadow mb-3" id="navbar">
            <div class="container-fluid">
               <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/icon1.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <a class="navbar-brand" id="link1" asp-area="" asp-controller="Home" asp-action="Index">на Главную</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a href="" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Контент</a>
                            <ul class="dropdown-menu-dark"
                            <li><a  class="nav-link text-light" id="link1" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a></li>
                            <li><a  class="nav-link text-light" id="link1" asp-area="" asp-controller="Product" asp-action="Index">Товары</a></li>
                            <li><a  class="nav-link text-light" id="link1" asp-area="" asp-controller="Auction" asp-action="Index">Аукцион</a></li>
                            <li><a  class="nav-link text-light" id="link1" asp-area="" asp-controller="Auctonbid" asp-action="Index">Ставки</a></li>
                           </ul>
                                <a  class="nav-link text-light" id="link1" asp-area="" asp-controller="Roles" asp-action="Index">Роли</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-light" id="link1" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RetroGamesAuction1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script defer src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script defer src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script defer src=""></script>
    <script defer src="~/lib/jquery/dist/jquery.min.js"></script>
    <script defer src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script defer src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>