Models/Auction.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RetroGamesAuction1.Models;

[Table("auction")]
public partial class Auction
{
    public Auction()
    {
        
        Auctionbid = new HashSet<Auctionbid>();
    }
    [Key]
    [Column("id_auction")]
    public int IdAuction { get; set; }

    [Column("id_product")]
    public int? IdProduct { get; set; }

    [Column("beginbid")]
    public int Beginbid { get; set; }

    [Column("begintime")]
    public DateTime? Begintime { get; set; }

    [Column("endtime")]
    public DateTime? Endtime { get; set; }
    [NotMapped]
    public DateTime DateTime { get; set; } = DateTime.Now;
    [NotMapped]
    public TimeSpan Date1 { get; set; }
    
    

    [ForeignKey("IdProduct")]
    [InverseProperty("Auction")]
    public virtual Product IdProductNavigation { get; set; }

    [InverseProperty("IdAuctionNavigation")]
    public virtual ICollection<Auctionbid> Auctionbid { get; } = new List<Auctionbid>();
}

Controllers/AuctionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using RetroGamesAuction1.Models;
using RetroGamesAuction1.Models.ViewModel;
using System.Linq.Expressions;
using NuGet.Packaging.Signing;
using System;
using System.Linq;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using RetroGamesAuction1.Services;

namespace RetroGamesAuction1.Controllers
{
    [Authorize]
    public class AuctionController : Controller
    {


        private readonly AuctionService _auctionService;
        public AuctionController(AuctionService auctionService)
        {

            _auctionService = auctionService;
        }

        // GET: Catalog1Controller
        public ActionResult Index(string searchBy, string searchValue)

        {

            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(_auctionService.SelectAuction());
            }
            else
            {
                if (searchBy.ToLower() == "productname")
                {
                    var searchByProductName = _auctionService.SelectAuction().Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "articul")
                {
                    var searchByProductArticul = _auctionService.SelectAuction().Where(p => p.Articul.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductArticul);
                }
                else if (searchBy.ToLower() == "beginbid")
                {
                    var searchByProductCost = _auctionService.SelectAuction().Where(c => c.Beginbid == int.Parse(searchValue));
                    return View(searchByProductCost);
                }
            }
            return View(_auctionService.SelectAuction());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AllIndex(string searchBy, string searchValue)

        {

            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(_auctionService.SelectAuction());
            }
            else
            {
                if (searchBy.ToLower() == "productname")
                {
                    var searchByProductName = _auctionService.SelectAuction().Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "articul")
                {
                    var searchByProductArticul = _auctionService.SelectAuction().Where(p => p.Articul.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductArticul);
                }
                else if (searchBy.ToLower() == "beginbid")
                {
                    var searchByProductCost = _auctionService.SelectAuction().Where(c => c.Beginbid == int.Parse(searchValue));
                    return View(searchByProductCost);
                }
            }
            return View(_auctionService.SelectAuction());
        }

        public ActionResult Details(int id)
        {
            _auctionService.SelectAuctionById(id);

            return View(_auctionService.SelectAuctionById(id));
        }
        
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            Auction auction = new Auction();

            return View(auction);
        }

        [Authorize(Roles = "Admin")]
        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Auction auction)
        {
            _auctionService.SaveAuction(auction);
            TempData["AlertMessage"] = "Ayкцион Создан!";
            return RedirectToAction(nameof(AllIndex));
        }

        // GET: AuctionController/Edit/5
        public ActionResult Edit(int id)
        {
            var auction = _auctionService.GetAuctionByID(id);
            return View(auction);
        }

        // POST: AuctionController/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Auction auction,int id)
        {
            var auctionUpdate = _auctionService.GetAuctionByID(id);
            auctionUpdate.Begintime = _auctionService.GetAuctionByID(id).Begintime;
            auctionUpdate.Endtime = _auctionService.GetAuctionByID(id).Endtime;
            auctionUpdate.IdProduct = auction.IdProduct;
            auctionUpdate.Beginbid = auction.Beginbid;

            if (auction != null && auctionUpdate.Begintime.HasValue && auctionUpdate.Endtime.HasValue)
            {
                _auctionService.UpdateAuction(auction);
                TempData["AlertMessage"] = "Аукцион изменен!";
            }
            return RedirectToAction(nameof(AllIndex));
        }
        
        [Authorize(Roles = "Admin")]
        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            _auctionService.RemoveAuction(id);
            TempData["AlertMessage"] = "Aукцион удален!";
            return RedirectToAction(nameof(AllIndex));
        }
        
        [Authorize(Roles = "Admin")]
        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/AuctionbidController.cs
using Microsoft.AspNetCore.Mvc;

using RetroGamesAuction1.Models.ViewModel;
using RetroGamesAuction1.Models;
using RetroGamesAuction1.Services;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using NuGet.Protocol.Plugins;
using Newtonsoft.Json.Linq;
using NuGet.Protocol;
using NuGet.Versioning;

namespace RetroGamesAuction1.Controllers
{

    public class AuctionbidController : Controller
    {
        //private readonly AuctionService _auctionService;
        private readonly AuctionBidService _auctionBidService;
        public AuctionbidController(AuctionBidService auctionBidService/*, AuctionService auctionService*/)
        {

            _auctionBidService = auctionBidService;
            // _auctionService = auctionService;
        }

        [Authorize]
        public ActionResult Index(string searchBy, string searchValue)

        {

            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(_auctionBidService.SelectAuctionbid());
            }
            else
            {
                if (searchBy.ToLower() == "productname")
                {
                    var searchByProductName = _auctionBidService.SelectAuctionbid().Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "clientname")
                {
                    var searchByClientName = _auctionBidService.SelectAuctionbid().Where(p => p.ClientName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByClientName);
                }
                else if (searchBy.ToLower() == "status")
                {
                    var searchByStatus = _auctionBidService.SelectAuctionbid().Where(p => p.Status.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByStatus);
                }
                else if (searchBy.ToLower() == "idauction")
                {
                    var searchByIdAuction = _auctionBidService.SelectAuctionbid().Where(c => c.IdAuction == int.Parse(searchValue));
                    return View(searchByIdAuction);
                }
            }
            return View(_auctionBidService.SelectAuctionbid());
        }

        public ActionResult Details(int id)
        {
            _auctionBidService.SelectAuctionbidById(id);

            return View(_auctionBidService.SelectAuctionbidById(id));
        }

        public ActionResult DetailsID(string id)
        {
            _auctionBidService.SelectAuctionbidByUserId(User.FindFirstValue(ClaimTypes.NameIdentifier));

            return View(_auctionBidService.SelectAuctionbidByUserId(User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }

        [HttpGet]
        public IActionResult AddBid()
        {
            Auctionbid bid = new Auctionbid();

            return View(bid);
        }

        [HttpPost]
        public IActionResult AddBid(int id)
        {
            JsonResult jsonResult = new JsonResult(id);

            if (User.Identity.IsAuthenticated)
            {
                Auctionbid bid = new Auctionbid();
                int count = _auctionBidService.SelectAuctionbidById(id).Count();

                bid.IdAuction = id;
                //bid.ClientName = User.FindFirstValue(ClaimTypes.Name);//находит имя пользователя
                bid.IdClient = User.FindFirstValue(ClaimTypes.NameIdentifier);//находит id пользователя
                bid.ClientName = User.FindFirstValue(ClaimTypes.Name).ToString();
                bid.Datatime = DateTime.Now;
                bid.Bid = 50;
                bid.LastBid = (bid.Bid + (bid.Bid * count));
                
                var bidResult = _auctionBidService.AddBids(bid);
                if (bidResult) {
                    TempData["AlertMessage"] = "Ставка сделана!";
                    //jsonResult.Value = new { Success = true };
                }
                else {
                    TempData["AlertMessage"] = "невозможно сделать ставку!";
                    //jsonResult.Value = new { Success = false, Message = "невозможно сделать ставку!" };
                }
            }
            else
            {
                TempData["AlertMessage"] = "нужно зарегистрироваться, чтобы сделать ставку!";
                //jsonResult.Value = new { Success = false, Message = "нужно зарегистрироваться, чтобы сделать ставку!" };  
            }
            //return jsonResult;
            return RedirectToAction("Details", "Auction", new { id });

        }
        
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var auctionbid = _auctionBidService.GetAuctionBidByID(id);
            return View(auctionbid);
        }

        [Authorize(Roles = "Admin")]
        // POST: AuctionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,Auctionbid auctionbid)
        {
            var bidUpdate = _auctionBidService.GetAuctionBidByID(id);
            bidUpdate.Bid = auctionbid.Bid;
            bidUpdate.IdAuction= auctionbid.IdAuction;
            bidUpdate.IdClient= auctionbid.IdClient;
            bidUpdate.Datatime = _auctionBidService.GetAuctionBidByID(id).Datatime;
            bidUpdate.Status = auctionbid.Status;
            bidUpdate.LastBid= auctionbid.LastBid;
            bidUpdate.ClientName= auctionbid.ClientName;
            bidUpdate.Info= auctionbid.Info;
           
           if ( auctionbid != null || bidUpdate.Datatime.HasValue)
            {
                _auctionBidService.UpdateAuctionBid(id,auctionbid);
                TempData["AlertMessage"] = "Ставка изменена!";
            }
           
            return RedirectToAction(nameof(AllIndexbid));
        }
       
        [Authorize(Roles = "Admin")]
        public ActionResult AllIndexbid(string searchBy, string searchValue)

        {

            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Введите значение для поиска";
                return View(_auctionBidService.SelectAuctionbid());
            }
            else
            {
                if (searchBy.ToLower() == "productname")
                {
                    var searchByProductName = _auctionBidService.SelectAuctionbid().Where(p => p.ProductName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByProductName);
                }
                else if (searchBy.ToLower() == "clientname")
                {
                    var searchByClientName = _auctionBidService.SelectAuctionbid().Where(p => p.ClientName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByClientName);
                }
                else if (searchBy.ToLower() == "status")
                {
                    var searchByStatus = _auctionBidService.SelectAuctionbid().Where(p => p.Status.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByStatus);
                }
                else if (searchBy.ToLower() == "idauction")
                {
                    var searchByIdAuction = _auctionBidService.SelectAuctionbid().Where(c => c.IdAuction == int.Parse(searchValue));
                    return View(searchByIdAuction);
                }
            }
            return View(_auctionBidService.SelectAuctionbid());
        }

        [Authorize(Roles = "Admin")]
        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            _auctionBidService.RemoveAuctionBid(id);
            TempData["AlertMessage"] = "Ставка удалена!";
            return RedirectToAction(nameof(AllIndexbid));
        }

        // POST: ProductController/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
     

    [Authorize(Roles = "Admin")]
        public ActionResult Admin()
        {
            

            return View();
        }

        public ActionResult Pay()
        {


            return View();
        }

    }
}

Views/Auction/AllIndex.cshtml
@model IEnumerable<RetroGamesAuction1.Models.ViewModel.ListViewModel>
@{
    ViewData["Title"] = "AllIndex";
}
<br />
<h3>Аукционы</h3>


   
@if (@TempData["AlertMessage"] != null)
{
  <div class="alert alert-secondary">
    <strong>Ура! </strong>@TempData["AlertMessage"]
</div>  
}
<br />
<div class="align-self-lg-center">
    @using (Html.BeginForm("AllIndex", "Auction", FormMethod.Get))
    {
        <table>
            <tr>
                <td>
                    <span><b>Поиск по: </b></span>
                    @Html.RadioButton("searchBy","ProductName",true)
                    <text>Название продукта</text>
                    @Html.RadioButton("searchBy","Articul",true)
                    <text>Артикул</text>
                    @Html.RadioButton("searchBy","BeginBid")
                    <text>Начальная ставка</text>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.TextBox("searchValue",null,new {Class = "form-control",placeholder = "Введите значение поиска"})
                </td>
                <td>
                    <input type="submit" value="Поиск" class="btn btn-outline-success"/>
                </td>
            </tr>
        </table>
    }
</div>
<br />
 <a href="@Url.Action("Create","Auction","Auction")" class="btn btn-outline-primary">Создать</a>
 <br />
 <div class="container-fluid py-5 col-sm-12" >
     <div class="row">
      <table  id="table" class="table-rounded table-bordered col-sm-12 hover display compact" style="width:100%"  style="" >
       <thead>
        <tr>
             <th scope ="col">
                Id aукциона
            </th scope ="col">
            
            <th scope ="col">
                Изображение
            </th scope ="col">
            <th>
                Артикул
            </th>
            <th scope ="col">
                Товар
            </th>
            <th scope ="col">
                Описание товара
            </th>
            <th scope ="col">
                Начальная ставка
            </th>
            <th scope ="col">
                Начало аукциона
            </th>
            <th scope ="col">
                Окончание аукциона
            </th>
             <th scope ="col">
                Изменение
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdAuction)
                </td>
                
                <td>
                    <img class="imgpr" src="/@item.ProductPic" width="100" height="100" alt="картинка" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Articul)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Beginbid) 
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Begintime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Endtime)
                </td>
                <td> 
                    <a href="@Url.Action("Edit","Auction",new {@id=item.IdAuction})" class="btn btn-outline-primary col-12">Изменить</a>
                    <hr />
                    <a href="@Url.Action("Delete","Auction",new {@id=item.IdAuction})" class="btn btn-outline-danger col-12" onclick="return confirm('Вы правда хотите удалить продукт? @item.ProductName?')">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
</div>

Views/Auction/Create.cshtml
@model RetroGamesAuction1.Models.Auction
@{
    ViewData["Title"] = "Create";
    
}

<h1>Создать</h1>


<hr />
<div class="card" id="card1" style="width: 35rem;"
  <div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdProduct" class="control-label"></label>
                <input asp-for="IdProduct" class="form-control" />
                <span asp-validation-for="IdProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beginbid" class="control-label"></label>
                <input asp-for="Beginbid" class="form-control" />
                <span asp-validation-for="Beginbid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Begintime" class="control-label"></label>
                <input asp-for="Begintime" class="form-control" />
                <span asp-validation-for="Begintime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endtime" class="control-label"></label>
                <input asp-for="Endtime" class="form-control" />
                <span asp-validation-for="Endtime" class="text-danger"></span>
            </div>

            -
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
  </div>
</div>
<div>
    <a asp-action="Index" id="link1">Вернуться</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Auction/Details.cshtml
@model IEnumerable<RetroGamesAuction1.Models.ViewModel.ListViewModel>
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <head>
        <script src="/js/site.js"></script>

    <meta http-equiv="refresh" content="3">
    </head>
    <br>
@if (@TempData["AlertMessage"] != null)
{
    <div class="alert alert-secondary">
        <strong>Ура! </strong>@TempData["AlertMessage"]
    </div>
}

@foreach (var item in Model)
{
  <div class="card col-md-10" id="card1">
    <div class="DescriptionContainer">
            <div class="card col-md-5" id="card1">
               <h5 class="card-title">@item.ProductName</h5>
                <p class="card-text">@item.Description</p>
            </div>
            <div class="card col-md-5" id="card1">
                  @if (@item.Endtime > item.DateTime)
                   {
                    <p class="card-text">время до окончания аукциона:</p>
                    <p class="time-text" id="time-text">@item.Date1.Value.Days дней @item.Date1.Value.Hours часов @item.Date1.Value.Minutes минут @item.Date1.Value.Seconds секунд</p>
                    <p class="time-text"> </p>

                   }

                  @if (@item.Endtime == item.DateTime)
                  {
                    <p class="card-title" id="date1">Аукцион окончен</p>
                  }
                 @if (@item.Endtime < item.DateTime)
                  {
                    <p class="card-title" id="date1">Аукцион окончен</p>
                  }
                 <br>
                <a asp-action="Details" asp-controller="Auction" asp-route-id="@item.IdAuction" class="btn btn-outline-primary">Обновить информацию</a>
            </div>
             
     </div>
   <div id="MainImageConteiner" class="card col-md-10">
               <img id="MainImage" src="/@item.ProductPic" />
   </div>
             <div id="TrumbNailMainConteiner">
              <div class="TrumbConteiner">
                  <img  src="/@item.ProductPic" class="TrumbImage"/>
              </div>
              <div class="TrumbConteiner">
                <img src="/@item.ProductPic1" class="TrumbImage" />
              </div>
              <div class="TrumbConteiner">
                <img src="/@item.ProductPic2" class="TrumbImage" />
              </div>
        </div>

    </div>

    @* <div id="carousel" class="carousel slide rounded col-md-6">

        <div class="carousel-inner border-info mb-3 p-3 rounded ">
            <div class="carousel-item active">
                <img src="/@item.ProductPic" height="300px" class="d-block rounded " alt="товар">
            </div>
            <div class="carousel-item">
                <img src="/@item.ProductPic1" height="300px"  class="d-block rounded" alt="товар">
            </div>
            <div class="carousel-item">
                <img src="/@item.ProductPic2" height="300px" class="d-block rounded" alt="товар">
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>

    </div>*@
    <br />
   
    <a asp-action="Index" asp-controller="Auction"  class="btn btn-outline-primary">Вернуться</a>

    <a asp-action="Details" asp-controller="Auctionbid" asp-route-id="@item.IdAuction" class="btn btn-outline-primary">Посмотреть ставки</a>
    @if (@item.Endtime > item.DateTime)
    {
        <a asp-action="AddBid" asp-controller="Auctionbid" asp-route-id="@item.IdAuction" class="btn btn-outline-primary">Поставить</a>
    }
    <script src="/js/site.js"></script>
}

Views/Auction/Edit.cshtml
@model RetroGamesAuction1.Models.Auction
@{
    ViewData["Title"] = "Edit";

}

<h1>Изменить</h1>


<hr />
<div class="card" id="card1" style="width: 35rem;"
  <div class="row">
    <div class="col-md-4">
        <form asp-action="Edit"method="post" enctype="multipart/form-data" asp-controller="Auction">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAuction" />
            <div class="form-group">
                <label asp-for="IdProduct" class="control-label"></label>
                <input asp-for="IdProduct" class="form-control" value="@Model.IdProduct" />
                <span asp-validation-for="IdProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Beginbid" class="control-label"></label>
                <input asp-for="Beginbid" class="form-control" value="@Model.Beginbid"/>
                <span asp-validation-for="Beginbid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Begintime" class="control-label"></label>
                <input asp-for="Begintime" class="form-control" value="@Model.Begintime" />
                <span asp-validation-for="Begintime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endtime" class="control-label"></label>
                <input asp-for="Endtime" class="form-control" value="@Model.Endtime"/>
                <span asp-validation-for="Endtime" class="text-danger"></span>
            </div>

            -
            <div class="form-group">
                <input type="submit" value="Изменить" class="btn btn-primary" />
            </div>
        </form>
    </div>
  </div>
</div>
<div>
    <a asp-action="Index" id="link1">Вернуться</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Auction/Index.cshtml
@model IEnumerable<RetroGamesAuction1.Models.ViewModel.ListViewModel>
@{
    ViewData["Title"] = "Index";
    
}
<header>
    <script src="/js/site.js"></script>
    
    @*<meta http-equiv="refresh" content="2">*@
</header>
@if (@TempData["AlertMessage"] != null)
{
  <div class="alert alert-secondary">
    <strong>Ура! </strong>@TempData["AlertMessage"]
</div>  
}
<br />
<div>
    @using (Html.BeginForm("Index", "Auction", FormMethod.Get))
    {
        <table>
            <tr>
                <td>
                    <span><b>Поиск по: </b></span>
                    @Html.RadioButton("searchBy","ProductName",true)
                    <text>Название продукта</text>
                    @Html.RadioButton("searchBy","Articul",true)
                    <text>Артикул</text>
                    @Html.RadioButton("searchBy","BeginBid")
                    <text>Начальная ставка</text>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.TextBox("searchValue",null,new {Class = "form-control",placeholder = "Введите значение поиска"})
                </td>
                <td>
                    <input type="submit" value="Поиск" class="btn btn-outline-success"/>
                </td>
            </tr>
        </table>
    }
</div>

<br />

<div class="row">
		@foreach (var item in Model)
		{
			<div class="card p-3 m-3 col-4" id="card1">
            <img src="@item.ProductPic" class="img-fluid"  alt="...">
				<div class="card-body">
                    <p class="card-text">Артикул: @item.Articul</p>
					<h5 class="card-title">@item.ProductName</h5>
					
                    <h5 class="card-title">Начальная ставка @item.Beginbid  руб.</h5>
              

                
				</div>
            
                <div class="card-footer">
                @if (@item.Endtime > item.DateTime)
                {
                    <a asp-action="AddBid" asp-controller="Auctionbid" asp-route-id="@item.IdAuction" class="btn btn-outline-primary">Поставить</a>
                }

                <a asp-action="Details" asp-controller="Auction" asp-route-id="@item.IdAuction" class="btn btn-outline-primary">Подробности</a>
                </div>



			</div>
        
			
		}

</div>

<script src="/js/site.js"></script>